import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

// const outfit = Outfit({
//   variable: "--font-geist-sans",
//   weight: ["400", "500", "600", "700"]
// });

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["400", "500", "600", "700"],
});

// const ovo = Ovo({
//   variable: "--font-geist-sans",
//   weight: ["400"]
// });

const ovo = Ovo({
  subsets: ["latin"],
  variable: "--font-ovo",
  weight: ["400"],
});

export const metadata = {
  title: "Aufa Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.variable} ${ovo.variable} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
